require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe HourBankEmployeesController do

  # This should return the minimal set of attributes required to create a valid
  # HourBankEmployee. As you add validations to HourBankEmployee, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # HourBankEmployeesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all hour_bank_employees as @hour_bank_employees" do
      hour_bank_employee = HourBankEmployee.create! valid_attributes
      get :index, {}, valid_session
      assigns(:hour_bank_employees).should eq([hour_bank_employee])
    end
  end

  describe "GET show" do
    it "assigns the requested hour_bank_employee as @hour_bank_employee" do
      hour_bank_employee = HourBankEmployee.create! valid_attributes
      get :show, {:id => hour_bank_employee.to_param}, valid_session
      assigns(:hour_bank_employee).should eq(hour_bank_employee)
    end
  end

  describe "GET new" do
    it "assigns a new hour_bank_employee as @hour_bank_employee" do
      get :new, {}, valid_session
      assigns(:hour_bank_employee).should be_a_new(HourBankEmployee)
    end
  end

  describe "GET edit" do
    it "assigns the requested hour_bank_employee as @hour_bank_employee" do
      hour_bank_employee = HourBankEmployee.create! valid_attributes
      get :edit, {:id => hour_bank_employee.to_param}, valid_session
      assigns(:hour_bank_employee).should eq(hour_bank_employee)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new HourBankEmployee" do
        expect {
          post :create, {:hour_bank_employee => valid_attributes}, valid_session
        }.to change(HourBankEmployee, :count).by(1)
      end

      it "assigns a newly created hour_bank_employee as @hour_bank_employee" do
        post :create, {:hour_bank_employee => valid_attributes}, valid_session
        assigns(:hour_bank_employee).should be_a(HourBankEmployee)
        assigns(:hour_bank_employee).should be_persisted
      end

      it "redirects to the created hour_bank_employee" do
        post :create, {:hour_bank_employee => valid_attributes}, valid_session
        response.should redirect_to(HourBankEmployee.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved hour_bank_employee as @hour_bank_employee" do
        # Trigger the behavior that occurs when invalid params are submitted
        HourBankEmployee.any_instance.stub(:save).and_return(false)
        post :create, {:hour_bank_employee => {  }}, valid_session
        assigns(:hour_bank_employee).should be_a_new(HourBankEmployee)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        HourBankEmployee.any_instance.stub(:save).and_return(false)
        post :create, {:hour_bank_employee => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested hour_bank_employee" do
        hour_bank_employee = HourBankEmployee.create! valid_attributes
        # Assuming there are no other hour_bank_employees in the database, this
        # specifies that the HourBankEmployee created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        HourBankEmployee.any_instance.should_receive(:update_attributes).with({ "these" => "params" })
        put :update, {:id => hour_bank_employee.to_param, :hour_bank_employee => { "these" => "params" }}, valid_session
      end

      it "assigns the requested hour_bank_employee as @hour_bank_employee" do
        hour_bank_employee = HourBankEmployee.create! valid_attributes
        put :update, {:id => hour_bank_employee.to_param, :hour_bank_employee => valid_attributes}, valid_session
        assigns(:hour_bank_employee).should eq(hour_bank_employee)
      end

      it "redirects to the hour_bank_employee" do
        hour_bank_employee = HourBankEmployee.create! valid_attributes
        put :update, {:id => hour_bank_employee.to_param, :hour_bank_employee => valid_attributes}, valid_session
        response.should redirect_to(hour_bank_employee)
      end
    end

    describe "with invalid params" do
      it "assigns the hour_bank_employee as @hour_bank_employee" do
        hour_bank_employee = HourBankEmployee.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        HourBankEmployee.any_instance.stub(:save).and_return(false)
        put :update, {:id => hour_bank_employee.to_param, :hour_bank_employee => {  }}, valid_session
        assigns(:hour_bank_employee).should eq(hour_bank_employee)
      end

      it "re-renders the 'edit' template" do
        hour_bank_employee = HourBankEmployee.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        HourBankEmployee.any_instance.stub(:save).and_return(false)
        put :update, {:id => hour_bank_employee.to_param, :hour_bank_employee => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested hour_bank_employee" do
      hour_bank_employee = HourBankEmployee.create! valid_attributes
      expect {
        delete :destroy, {:id => hour_bank_employee.to_param}, valid_session
      }.to change(HourBankEmployee, :count).by(-1)
    end

    it "redirects to the hour_bank_employees list" do
      hour_bank_employee = HourBankEmployee.create! valid_attributes
      delete :destroy, {:id => hour_bank_employee.to_param}, valid_session
      response.should redirect_to(hour_bank_employees_url)
    end
  end

end
