require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ScheduledEmployesController do

  # This should return the minimal set of attributes required to create a valid
  # ScheduledEmploye. As you add validations to ScheduledEmploye, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ScheduledEmployesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all scheduled_employes as @scheduled_employes" do
      scheduled_employe = ScheduledEmploye.create! valid_attributes
      get :index, {}, valid_session
      assigns(:scheduled_employes).should eq([scheduled_employe])
    end
  end

  describe "GET show" do
    it "assigns the requested scheduled_employe as @scheduled_employe" do
      scheduled_employe = ScheduledEmploye.create! valid_attributes
      get :show, {:id => scheduled_employe.to_param}, valid_session
      assigns(:scheduled_employe).should eq(scheduled_employe)
    end
  end

  describe "GET new" do
    it "assigns a new scheduled_employe as @scheduled_employe" do
      get :new, {}, valid_session
      assigns(:scheduled_employe).should be_a_new(ScheduledEmploye)
    end
  end

  describe "GET edit" do
    it "assigns the requested scheduled_employe as @scheduled_employe" do
      scheduled_employe = ScheduledEmploye.create! valid_attributes
      get :edit, {:id => scheduled_employe.to_param}, valid_session
      assigns(:scheduled_employe).should eq(scheduled_employe)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ScheduledEmploye" do
        expect {
          post :create, {:scheduled_employe => valid_attributes}, valid_session
        }.to change(ScheduledEmploye, :count).by(1)
      end

      it "assigns a newly created scheduled_employe as @scheduled_employe" do
        post :create, {:scheduled_employe => valid_attributes}, valid_session
        assigns(:scheduled_employe).should be_a(ScheduledEmploye)
        assigns(:scheduled_employe).should be_persisted
      end

      it "redirects to the created scheduled_employe" do
        post :create, {:scheduled_employe => valid_attributes}, valid_session
        response.should redirect_to(ScheduledEmploye.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved scheduled_employe as @scheduled_employe" do
        # Trigger the behavior that occurs when invalid params are submitted
        ScheduledEmploye.any_instance.stub(:save).and_return(false)
        post :create, {:scheduled_employe => {  }}, valid_session
        assigns(:scheduled_employe).should be_a_new(ScheduledEmploye)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ScheduledEmploye.any_instance.stub(:save).and_return(false)
        post :create, {:scheduled_employe => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested scheduled_employe" do
        scheduled_employe = ScheduledEmploye.create! valid_attributes
        # Assuming there are no other scheduled_employes in the database, this
        # specifies that the ScheduledEmploye created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ScheduledEmploye.any_instance.should_receive(:update_attributes).with({ "these" => "params" })
        put :update, {:id => scheduled_employe.to_param, :scheduled_employe => { "these" => "params" }}, valid_session
      end

      it "assigns the requested scheduled_employe as @scheduled_employe" do
        scheduled_employe = ScheduledEmploye.create! valid_attributes
        put :update, {:id => scheduled_employe.to_param, :scheduled_employe => valid_attributes}, valid_session
        assigns(:scheduled_employe).should eq(scheduled_employe)
      end

      it "redirects to the scheduled_employe" do
        scheduled_employe = ScheduledEmploye.create! valid_attributes
        put :update, {:id => scheduled_employe.to_param, :scheduled_employe => valid_attributes}, valid_session
        response.should redirect_to(scheduled_employe)
      end
    end

    describe "with invalid params" do
      it "assigns the scheduled_employe as @scheduled_employe" do
        scheduled_employe = ScheduledEmploye.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ScheduledEmploye.any_instance.stub(:save).and_return(false)
        put :update, {:id => scheduled_employe.to_param, :scheduled_employe => {  }}, valid_session
        assigns(:scheduled_employe).should eq(scheduled_employe)
      end

      it "re-renders the 'edit' template" do
        scheduled_employe = ScheduledEmploye.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ScheduledEmploye.any_instance.stub(:save).and_return(false)
        put :update, {:id => scheduled_employe.to_param, :scheduled_employe => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested scheduled_employe" do
      scheduled_employe = ScheduledEmploye.create! valid_attributes
      expect {
        delete :destroy, {:id => scheduled_employe.to_param}, valid_session
      }.to change(ScheduledEmploye, :count).by(-1)
    end

    it "redirects to the scheduled_employes list" do
      scheduled_employe = ScheduledEmploye.create! valid_attributes
      delete :destroy, {:id => scheduled_employe.to_param}, valid_session
      response.should redirect_to(scheduled_employes_url)
    end
  end

end
